/* ============================================================
   kumbuka.ai · Team & users
   ============================================================ */

function TeamUsers({ users, setUsers }) {
  const toast = useToast();
  const menu = useMenu();
  const [query, setQuery] = useState('');
  const [roleFilter, setRoleFilter] = useState('all');
  const [editor, setEditor] = useState(false);
  const [confirm, setConfirm] = useState(null);

  let rows = users.slice();
  if (roleFilter !== 'all') rows = rows.filter(u => roleFilter === 'admin' ? u.role === 'admin' : u.role === 'member');
  if (query.trim()) {
    const q = query.toLowerCase();
    rows = rows.filter(u => u.name.toLowerCase().includes(q) || u.email.toLowerCase().includes(q));
  }
  const adminCount = users.filter(u => u.role === 'admin' && u.status !== 'disabled').length;

  const setUser = (id, patch) => setUsers(prev => prev.map(u => u.id === id ? { ...u, ...patch } : u));

  const createUser = (data) => {
    const initials = (data.name || data.email).split(/[\s@.]+/).filter(Boolean).slice(0, 2).map(s => s[0].toUpperCase()).join('');
    const nu = { id: 'u-' + Math.random().toString(36).slice(2), name: data.name || data.email.split('@')[0], email: data.email, initials, role: data.role, status: 'invited', last: 'never' };
    setUsers(prev => [...prev, nu]);
    toast('Invite sent via ' + IDP_NAME, { icon: 'userPlus' });
    setEditor(false);
  };

  const userMenu = (ev, u) => {
    const lastAdminGuard = u.role === 'admin' && adminCount <= 1;
    menu.open(ev, [
      { icon: 'swap', label: u.role === 'admin' ? 'Make member' : 'Make admin',
        disabled: lastAdminGuard && u.role === 'admin',
        onClick: () => { setUser(u.id, { role: u.role === 'admin' ? 'member' : 'admin' }); toast(u.name + ' is now ' + (u.role === 'admin' ? 'a member' : 'an admin'), { icon: 'shield' }); } },
      { icon: 'reset', label: 'Reset password',
        onClick: () => setConfirm({
          eyebrow: 'reset password', title: 'Send a password reset?',
          body: 'A reset link is generated by ' + IDP_NAME + ' and emailed to the member. Their current session stays valid until they complete it.',
          target: u.email, confirmLabel: 'Send reset', confirmIcon: 'reset',
          onConfirm: () => toast('Reset link sent to ' + u.email, { icon: 'reset' }) }) },
      { sep: true },
      u.status === 'disabled'
        ? { icon: 'shield', label: 'Enable account', onClick: () => { setUser(u.id, { status: 'active', last: 'just now' }); toast(u.name + ' enabled', { icon: 'check' }); } }
        : { icon: 'eyeOff', label: 'Disable account', danger: true, disabled: u.self || (u.role === 'admin' && lastAdminGuard),
            onClick: () => setConfirm({
              eyebrow: 'disable account', title: 'Disable ' + u.name + '?', danger: true,
              body: u.role === 'admin'
                ? 'They lose console and API access immediately. ' + IDP_NAME + ' suspends the account; their private memory is untouched and stays theirs.'
                : 'They lose console and API access immediately. ' + IDP_NAME + ' suspends the account; their private memory is untouched and stays theirs.',
              target: u.email, confirmLabel: 'Disable', confirmIcon: 'eyeOff',
              onConfirm: () => { setUser(u.id, { status: 'disabled', last: 'just now' }); toast(u.name + ' disabled', { icon: 'eyeOff' }); } }) },
    ]);
  };

  const statusLabel = { active: 'Active', disabled: 'Disabled', invited: 'Invite sent' };

  return (
    <div className="team-screen">
      <div className="idp-banner">
        <Icon name="shield" />
        <span>Accounts are managed in <span className="idp-name">{IDP_NAME}</span>. <b>Create</b>, <b>disable</b>, <b>reset</b>, and <b>role</b> changes here write through to the directory — they are not local to this console.</span>
        <a href="#" onClick={(e) => { e.preventDefault(); toast('Opening identity provider…', { icon: 'link' }); }}>Open {IDP_NAME} →</a>
      </div>

      <div className="team-toolbar">
        <div className="search" style={{ maxWidth: 320 }}>
          <Icon name="search" />
          <input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name or email…" aria-label="Search members" />
        </div>
        <div className="seg" role="group" aria-label="Filter by role">
          <button className={roleFilter === 'all' ? 'on' : ''} onClick={() => setRoleFilter('all')}>All</button>
          <button className={roleFilter === 'admin' ? 'on' : ''} onClick={() => setRoleFilter('admin')}>Admins</button>
          <button className={roleFilter === 'member' ? 'on' : ''} onClick={() => setRoleFilter('member')}>Members</button>
        </div>
        <span className="result-count">{rows.length} of {users.length}</span>
        <span className="spacer"></span>
        <button className="btn primary" onClick={() => setEditor(true)}><Icon name="userPlus" /><span className="txt">Invite member</span></button>
      </div>

      <div className="team-body">
        <table className="utable">
          <thead>
            <tr>
              <th style={{ width: '38%' }}>Member</th>
              <th style={{ width: 140 }}>Role</th>
              <th style={{ width: 150 }}>Status</th>
              <th style={{ width: 150 }}>Last active</th>
              <th style={{ width: 56 }} aria-label="Actions"></th>
            </tr>
          </thead>
          <tbody>
            {rows.map(u => (
              <tr key={u.id} className={u.status === 'disabled' ? 'u-disabled' : ''}>
                <td>
                  <div className="u-id">
                    <Avatar person={u} />
                    <div>
                      <div className="u-name">{u.name}{u.self && <span className="scope-flag" style={{ marginLeft: 9 }}>you</span>}</div>
                      <div className="u-email">{u.email}</div>
                    </div>
                  </div>
                </td>
                <td><RoleBadge role={u.role} /></td>
                <td><span className={'ustatus ' + u.status}><span className="dot"></span>{statusLabel[u.status]}</span></td>
                <td><span className="u-last">{u.last}</span></td>
                <td>
                  <button className="row-menu-btn" style={{ opacity: 1 }} aria-label={'Actions for ' + u.name} onClick={(ev) => userMenu(ev, u)}><Icon name="dots" /></button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {rows.length === 0 && (
          <div className="state">
            <div className="state-mark"><Icon name="users" /></div>
            <h3>No members match</h3>
            <p>Adjust the search or role filter to see the rest of the team.</p>
          </div>
        )}
      </div>

      {editor && <UserEditor onClose={() => setEditor(false)} onSave={createUser} />}
      {confirm && <ConfirmModal {...confirm} onClose={() => setConfirm(null)} />}
      {menu.node}
    </div>
  );
}

Object.assign(window, { TeamUsers });
